artist:
  name: The Bluebird Two
  tagline: DIY Indie from ATL, GA
  # seo_title:
  # seo_description:
  # contact_twitter_username: @thebluebirdtwo
  # contact_phone: 
  # contact_email: bookthebluebirdtwo@gmail.com

social:
  - name: Facebook
    url: http://facebook.com/thebluebirdtwo
  - name: Instagram
    url: http://instagram.com/thebluebirdtwo
  - name: bandcamp
    url: http://thebluebirdtwo.bandcamp.com/
  - name: Spotify
    url: https://open.spotify.com/artist/3DUpMyQRofZal4rYRpDnxK?si=PDmCJRmBTU2bpPC1pT_6Lg
  - name: Youtube
    url: https://www.youtube.com/channel/UCsXFTuDCx8uAA7ikUsShwXA
site_language: en
